runtime: python311

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
  
libraries:
  # create secure connections between the client and server
  - name: ssl
    version: latest
